title: "Matteo Sesia"
email: "you@example.com"
description: >-
  Official academic website
baseurl: ""
url: "https://msesia.github.io"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-archives

minimal_mistakes_skin: contrast
markdown: kramdown
highlighter: rouge

author:
  name   : "Matteo Sesia"
  avatar : "/assets/images/headshot.jpg"
  bio    : >
    Statistician and Data Scientist.  
    Assistant Professor at the University of Southern California.

  location : "Los Angeles, CA"
  email    : "sesia@marshall.usc.edu"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/msesia"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=qFtP1MQAAAAJ&hl=en"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0001-9046-907X"

include:
  - .htaccess

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/
  publications:
    output: true
    permalink: /publications/:title/
  teaching:
    output: true
    permalink: /teaching/:title/